version: '3.8'

services:
  python-app:
    build: ./python
    ports:
      - "8080:8080"
    restart: unless-stopped

  java-app:
    build:
      context: ./java
      dockerfile: multi-stage.Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    restart: unless-stopped
